### PR TITLE
[test] Add initial framework for integration testing

### PR DESCRIPTION
**Pull request by mojoX911**
This PR adds an integration test which is same as the example coinswap workflow given in Readme.md. 

To run the test, it needs a running bitcoin core node with a wallet named `teleport` loaded and having enough balance to perform transactions.

This adds a kill switch mechanism to stop the maker server when the test completes. 

Assertions are preliminary. It may require further additions. 

[update]
Integration test is ignored by default as it will fail the current CI. Will update the CI later to properly handle it.

### CODE REVIEW

**Comment by chris-belcher** [comment]
Hello sorry for the delay.

I've had one read through the code and it looks okay. I'll try out the test for myself shortly.

**Comment by mojoX911** [comment]
@chris-belcher no issues, let me know it passes. Its might be a little tricky to get the full test passed automatically.

### Update
I have added CI coverage for integration testing.

Along with some minor refactoring. 

Unfortunately the CI isn't passing right now, because the CI build script is still the old one. And updated CI will not work
until its merged.  Its trying with the old CI script, check here https://github.com/bitcoin-teleport/teleport-transactions/actions/runs/889728518/workflow.

It is working in my own branch though, because I guess github automatically updates CI scripts for own repo.
https://github.com/mojoX911/teleport-transactions/pull/4

the tests passing at `00ee01c`

**Comment by mojoX911** [comment]
@chris-belcher no issues. It might take some tries to get the int test working.

### Update

I have made some minor refactoring and updated the CI build script to include integration testing. CI is now covering all the test.

Good thing is the int test also increased the repo coverage report significantly. We are at ~86% . :)

**Comment by chris-belcher** [comment]
Ran the test and it succeeded in making a coinswap, but failed with this error:

```
successfully completed coinswap
accepted connection from 127.0.0.1:50958
Kill signal recieved, stoping maker....
successfully completed coinswap
==> None
reached EOF
accepted connection from 127.0.0.1:50960
ok
accepted connection from 127.0.0.1:39574
Kill signal recieved, stoping maker....
accepted connection from 127.0.0.1:39576
ok
reached EOF
thread 'test::test_standard_coin_swap' panicked at 'assertion failed: `(left == right)`
  left: `Amount(14974828 satoshi)`,
 right: `Amount(14975410 satoshi)`', src/main.rs:486:9
```

No idea why the balance is slightly different, maybe my node spent a different amount on miner fees. But its most likely to be some irrelevant detail.

So I'd suggest instead of checking the exact balance down to the last satoshi, just checking that the maker's balances have gone above 0.15btc and the taker's balance has gone below, because that's the important thing that the makers earn money and takers spend it.

**Comment by mojoX911** [comment]
> So I'd suggest instead of checking the exact balance down to the last satoshi, just checking that the maker's balances have gone above 0.15btc and the taker's balance has gone below (but not by too much)

Noted. Ya makes sense not to test amount with too much granularity. Will update.

**Comment by chris-belcher** [comment]
I pushed some suggested edits

**Comment by mojoX911** [comment]
tACK `c2ef4ca`. Looks good..

**Comment by chris-belcher** [comment]
Was playing around and noticed I could remove one Arc pointer without changing anything. Not too sure myself why this works, presumably because the first variable never gets Copy'd (?)

The whole code looks fine to me. When you're ready could you squish the commits down where each commit is a logical whole (not necessarily into just one commit)

**Comment by mojoX911** [comment]
> Was playing around and noticed I could remove one Arc pointer without changing anything. Not too sure myself why this works, presumably because the first variable never gets Copy'd (?)

Ya that seems to work. No idea why. Probably I was trying different things to make it work and ended up taking redundant clones. 


>The whole code looks fine to me. When you're ready could you squish the commits down where each commit is a logical whole (not necessarily into just one commit)

Refactored commits into logical chunks.

**Pull request merged**
