### PR TITLE
use Script::new_p2pkh for creating P2PKH scriptPubKey

### PR DESCRIPTION
**Pull request by theStack**
This is a simple refactor PR that takes advantage of `Script::new_p2pkh()` from the bitcoin crate (see https://docs.rs/bitcoin/0.25.2/bitcoin/blockdata/script/struct.Script.html#method.new_p2pkh, avilable since 0.25.1) for creating a P2PKH output script rather than crafting it by hand. Also, for calculating the hash from the pubkey, it's `pubkey_hash()` method (https://docs.rs/bitcoin/0.25.2/bitcoin/util/key/struct.PublicKey.html#method.pubkey_hash -- available since 0.25.1) is used instead of `hashes::hash160`.

The implementation of `Script::new_p2pkh()` actually looks quite similar to what is replaced:
https://github.com/rust-bitcoin/rust-bitcoin/blob/b48f374c2cd6127aaa5e8b2ffbed80c3aa03245c/src/blockdata/script.rs#L238-L247

Note that I'm a total Rust noob, but at least the silent output of `cargo build` gives me some confidence that the change works 😎

### CODE REVIEW

**Comment by chris-belcher** [comment]
Thanks for the PR, I'll review it shortly

**Comment by chris-belcher** [comment]
Reviewed and tested. Looks good to me.

However please change the commit message. [Use the body to explain what and why vs. how](https://chris.beams.io/posts/git-commit/#why-not-how). I suggest something like "Replaced verbose code with call to rust-bitcoin"

**Comment by theStack** [comment]
Thanks for reviewing. Forced-pushed with updated commit body.

**Comment by chris-belcher** [comment]
I mean you should remove the text `Use Script::new_p2pkh for creating P2PKH scriptPubKey` because it explains how, rather than what and why. The first line should be `Replaced verbose code with calls to rust-bitcoin` (without the trailing period). Sorry to be like this about messages, but its surprisingly important.

**Comment by theStack** [comment]
Ah, got it, I was reading sloppily and thought the commit message _body_ was not detailled enough. Forced-pushed a new version. Note that I also considered to [use the imperative mood in the subject line](https://chris.beams.io/posts/git-commit/#imperative) (i.e. "replace" instead of "replaced") ;)

**Comment by chris-belcher** [comment]
Ah yes that's right, I forgot about the imperative mood.

**Pull request merged**
